DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzM4MjI1MzE4LCJ1c2VySWQiOjJ9.6jb27zof9Gok2VRQuyi0-nhGNoyyHqNlB3lkaV55q7w
